apiVersion: v1
kind: Service
metadata:
 name: vpc-nlb-publico
 annotations:
   service.kubernetes.io/ibm-load-balancer-cloud-provider-enable-features: "nlb"
   service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: "public"
   service.kubernetes.io/ibm-load-balancer-cloud-provider-vpc-subnets: "0767-5fe01a4c-03bf-419c-a09e-86ae1bb2af1d"
   service.kubernetes.io/ibm-load-balancer-cloud-provider-zone: "us-east-2"
spec:
 type: LoadBalancer
 selector:
   deployment: listas-1
 ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
 externalTrafficPolicy: Local
